### ISSUE TITLE
Use more `session_name_path_components` only if needed

### ISSUE THREAD

**Issue by praveenperera** [vinnymeller/twm#1]
Have an option for the session name path components to be dynamic. Default to 1, go to 2,3,4 if session names already exists. 

If this sounds good but you don't have time to implement it let me know I can take a crack at it tomorrow.

**Comment by vinnymeller** [comment]
Thanks for the suggestion! Since discovering I can set environment variables through tmux (and adding the `TWM_` vars to the sessions) I've had this on the back of my mind.

Does the following logic make sense to you?

1. Generate the session name from the path
2. If a session with the same name already exists, check to see if the `TWM_ROOT` environment variable for the session matches the path to the workspace being opened (`tmux showenv -t [session_name]`)
    - If so, we're done, open that workspace. If not, continue
3. Increment the configured `session_name_path_components` value and go back to step 1


If that sounds good I'll be happy to implement it later today

**Comment by praveenperera** [comment]
Ya that makes sense to me.

I was thinking always open a new session, because I currently use thuanOwa/tmux-fzf-session-switch to switch between existing sessions. 

I think your idea is better tho, i’m assuming more people would want to switch to a session if it already exists rather than open another session in the directory.

**Comment by vinnymeller** [comment]
Pushed the new version to crates.io. Let me know if you have any issues!

**Comment by praveenperera** [comment]
Tried it out works great thanks @vinnymeller 

Closed by #2
