### ISSUE TITLE
But... what does it do?

### ISSUE THREAD

**Issue by nyarly** [vinnymeller/twm#43]
I'm looking at Tmux session management tools and found twm via nixpkgs.

The README copies the help text from `twm`, but it's unclear what will happen if I run `twm`.

After some time, I'm getting back into web app development, and would like to be able to quickly open 6 windows in a session. I already have a fish event handler script that launches tmux for me automatically; I'm considering adding a direnv config to trigger a different handler for a session manager, if it makes sense to do so. Can `tmw` help me in this scenario?

Ideally, the README would have answered this question in the first couple of paragraphs.

**Comment by vinnymeller** [comment]
if you run `twm`, a fuzzy finder window (basically just like fzf or similar) opens up with all _workspaces_ you have

workspaces can be any folder, but what exactly counts as a workspace for you is configurable. it defaults to any git repo within your home directory, or one with a `.twm.yaml` file in it

each workspace will be opened in a unique session. what happens when you open a session is also configurable.

each workspace will have a _type_ based on your configuration. each workspace type may have a default _layout_. or you can override default layouts by adding a `.twm.yaml` to a project's root directory and defining a layout there

layouts let you send arbitrary tmux commands to your new session. if you look at the example config here, you'll see how all of these things are configured: https://github.com/vinnymeller/twm/blob/master/doc/CONFIGURATION.md#example-twm-config

i use it similarly to the example config with setting up different layouts for projects in different languages, e.g. different hot reload commands, test runners, etc

based on your description i think using a session manager of some sort makes sense. be sure to check out the "similar projects" section if you haven't already for tools that may suit your needs better: https://github.com/vinnymeller/twm?tab=readme-ov-file#similar-projects

also I will look into clarifying the readme :+1:

**Comment by nyarly** [comment]
Thanks! That's really helpful.

I notice your keybindings for `tmux neww twm` - does that let twm record the new window as part of the session or something?

For running stuff in the workspace, I'm already fooling with `process-compose` - using tmux as the "init" for my dev env might make sense (and I've done that in the misty past (oh, no actually it was screen...)) but so far `process-compose` does what I want. Except for Parcel... but I'm chalking that up to Node

**Comment by vinnymeller** [comment]
> I notice your keybindings for tmux neww twm - does that let twm record the new window as part of the session or something?

it will open a window in your current session but the window will die when a selection is made or it's canceled

alternatively in my actual config i also have `bind o display-popup -E "twm"` bound to just open the picker in a popup instead of a new window in current session

just checked out process compose, hadn't heard of it before. does each project get a `project-compose.yaml`? and do you run `process-compose` to start stuff up?

i might be a bit dumb but i quickly tried seeing if I could get it to work to have `htop` and `cargo watch -x test` running (commands I'd normally have running in different windows or panes in a session)

can you explain a bit more what your workflow looks like?
